from fastapi import APIRouter
from typing import List
from app.schemas import IpoItem, BondItem, EtfItem

router = APIRouter(prefix="/discovery", tags=["Discovery Hub"])

@router.get("/ipos", response_model=List[IpoItem])
def get_ipos():
    """Live 2026 IPO Discovery Engine with Grey Market Premium (GMP) & Real-time Subscriptions."""
    return [
        IpoItem(
            company_name="NTPC Green Energy Ltd",
            companyName="NTPC Green Energy Ltd",
            symbol="NTPCGREEN",
            status="OPEN",
            subscriptionStatus="5.82x Subscribed (OPEN)",
            price_band="₹102 - ₹108",
            issuePriceBand="₹102 - ₹108",
            issue_size_cr=10000.0,
            lot_size=138,
            lotSize=138,
            bidding_dates="Aug 27 - Aug 29",
            issueOpenDate="2026-08-27",
            issueCloseDate="2026-08-29",
            listingDate="2026-09-03",
            gmp_pts=18.50,
            gmp_pct=17.13,
            subscription_rate_x=5.82,
            retail_subscription_x=6.40,
            qib_subscription_x=7.95,
            nii_subscription_x=3.10,
            ai_verdict="SUBSCRIBE (Green Energy Leader)"
        ),
        IpoItem(
            company_name="Swiggy Delivery Solutions Ltd",
            companyName="Swiggy Delivery Solutions Ltd",
            symbol="SWIGGY",
            status="OPEN",
            subscriptionStatus="3.45x Subscribed (OPEN)",
            price_band="₹370 - ₹390",
            issuePriceBand="₹370 - ₹390",
            issue_size_cr=11327.0,
            lot_size=38,
            lotSize=38,
            bidding_dates="Aug 26 - Aug 29",
            issueOpenDate="2026-08-26",
            issueCloseDate="2026-08-29",
            listingDate="2026-09-04",
            gmp_pts=32.0,
            gmp_pct=8.21,
            subscription_rate_x=3.45,
            retail_subscription_x=4.12,
            qib_subscription_x=4.85,
            nii_subscription_x=1.80,
            ai_verdict="SUBSCRIBE (Quick-Commerce Scale)"
        ),
        IpoItem(
            company_name="Waaree Energies Ltd",
            companyName="Waaree Energies Ltd",
            symbol="WAAREE",
            status="UPCOMING",
            subscriptionStatus="Upcoming (Opens Sep 03)",
            price_band="₹1,427 - ₹1,503",
            issuePriceBand="₹1,427 - ₹1,503",
            issue_size_cr=4321.0,
            lot_size=9,
            lotSize=9,
            bidding_dates="Sep 03 - Sep 06",
            issueOpenDate="2026-09-03",
            issueCloseDate="2026-09-06",
            listingDate="2026-09-11",
            gmp_pts=680.0,
            gmp_pct=45.24,
            subscription_rate_x=0.0,
            retail_subscription_x=0.0,
            qib_subscription_x=0.0,
            nii_subscription_x=0.0,
            ai_verdict="SUBSCRIBE (High GMP Conviction)"
        ),
        IpoItem(
            company_name="Hyundai Motor India Ltd",
            companyName="Hyundai Motor India Ltd",
            symbol="HYUNDAI",
            status="UPCOMING",
            subscriptionStatus="Upcoming (Opens Sep 12)",
            price_band="₹1,850 - ₹1,960",
            issuePriceBand="₹1,850 - ₹1,960",
            issue_size_cr=27870.0,
            lot_size=7,
            lotSize=7,
            bidding_dates="Sep 12 - Sep 15",
            issueOpenDate="2026-09-12",
            issueCloseDate="2026-09-15",
            listingDate="2026-09-20",
            gmp_pts=145.0,
            gmp_pct=7.40,
            subscription_rate_x=0.0,
            retail_subscription_x=0.0,
            qib_subscription_x=0.0,
            nii_subscription_x=0.0,
            ai_verdict="SUBSCRIBE (Mega-Cap Anchor)"
        ),
        IpoItem(
            company_name="Premier Energies Ltd",
            companyName="Premier Energies Ltd",
            symbol="PREMIERENE",
            status="CLOSED",
            subscriptionStatus="74.38x Subscribed (CLOSED)",
            price_band="₹427 - ₹450",
            issuePriceBand="₹427 - ₹450",
            issue_size_cr=2830.0,
            lot_size=33,
            lotSize=33,
            bidding_dates="Aug 20 - Aug 23",
            issueOpenDate="2026-08-20",
            issueCloseDate="2026-08-23",
            listingDate="2026-08-28",
            gmp_pts=390.0,
            gmp_pct=86.67,
            subscription_rate_x=74.38,
            retail_subscription_x=25.40,
            qib_subscription_x=216.67,
            nii_subscription_x=50.04,
            ai_verdict="SUBSCRIBE (Blockbuster Listing)"
        ),
        IpoItem(
            company_name="Bajaj Housing Finance Ltd",
            companyName="Bajaj Housing Finance Ltd",
            symbol="BAJAJHFL",
            status="CLOSED",
            subscriptionStatus="63.61x Subscribed (CLOSED)",
            price_band="₹66 - ₹70",
            issuePriceBand="₹66 - ₹70",
            issue_size_cr=6560.0,
            lot_size=214,
            lotSize=214,
            bidding_dates="Aug 14 - Aug 18",
            issueOpenDate="2026-08-14",
            issueCloseDate="2026-08-18",
            listingDate="2026-08-23",
            gmp_pts=65.0,
            gmp_pct=92.86,
            subscription_rate_x=63.61,
            retail_subscription_x=7.41,
            qib_subscription_x=209.36,
            nii_subscription_x=41.51,
            ai_verdict="SUBSCRIBE (High Listing Gains)"
        ),
        IpoItem(
            company_name="Hexaware Technologies Ltd",
            companyName="Hexaware Technologies Ltd",
            symbol="HEXAWARE",
            status="UPCOMING",
            subscriptionStatus="Upcoming (Opens Oct 10)",
            price_band="₹680 - ₹720",
            issuePriceBand="₹680 - ₹720",
            issue_size_cr=9950.0,
            lot_size=20,
            lotSize=20,
            bidding_dates="Oct 10 - Oct 14",
            issueOpenDate="2026-10-10",
            issueCloseDate="2026-10-14",
            listingDate="2026-10-19",
            gmp_pts=115.0,
            gmp_pct=15.97,
            subscription_rate_x=0.0,
            retail_subscription_x=0.0,
            qib_subscription_x=0.0,
            nii_subscription_x=0.0,
            ai_verdict="SUBSCRIBE (IT Services Re-listing)"
        ),
        IpoItem(
            company_name="NSDL Depositary India Ltd",
            companyName="NSDL Depositary India Ltd",
            symbol="NSDL",
            status="UPCOMING",
            subscriptionStatus="Upcoming (Opens Oct 18)",
            price_band="₹740 - ₹800",
            issuePriceBand="₹740 - ₹800",
            issue_size_cr=4500.0,
            lot_size=18,
            lotSize=18,
            bidding_dates="Oct 18 - Oct 22",
            issueOpenDate="2026-10-18",
            issueCloseDate="2026-10-22",
            listingDate="2026-10-27",
            gmp_pts=210.0,
            gmp_pct=26.25,
            subscription_rate_x=0.0,
            retail_subscription_x=0.0,
            qib_subscription_x=0.0,
            nii_subscription_x=0.0,
            ai_verdict="SUBSCRIBE (Monopoly Financial Infra)"
        )
    ]

@router.get("/bonds", response_model=List[BondItem])
def get_bonds():
    """Fixed Income & Debt Market Hub (SGBs, G-Secs, Corporate Bonds) with 2026 Yields."""
    return [
        BondItem(
            bond_name="Sovereign Gold Bond 2028-29 Series IV (SGB)",
            name="Sovereign Gold Bond 2028-29 Series IV (SGB)",
            symbol="SGB2029IV",
            isin="IN0020210252",
            category="SGB",
            issuer="Reserve Bank of India (RBI)",
            coupon_rate_pct=2.50,
            couponRate=2.50,
            ytm_pct=9.40,
            ytm=9.40,
            rating="Sovereign (AAA)",
            face_value=5850.0,
            faceValue=5850.0,
            market_price=7180.0,
            ltp=7180.0,
            maturity_date="2029-02-15",
            maturityDate="2029-02-15",
            tax_status="Tax-Free Capital Gains upon Maturity"
        ),
        BondItem(
            bond_name="Sovereign Gold Bond 2030 Series I (SGB)",
            name="Sovereign Gold Bond 2030 Series I (SGB)",
            symbol="SGB2030I",
            isin="IN0020220015",
            category="SGB",
            issuer="Reserve Bank of India (RBI)",
            coupon_rate_pct=2.50,
            couponRate=2.50,
            ytm_pct=9.85,
            ytm=9.85,
            rating="Sovereign (AAA)",
            face_value=6120.0,
            faceValue=6120.0,
            market_price=7240.0,
            ltp=7240.0,
            maturity_date="2030-06-20",
            maturityDate="2030-06-20",
            tax_status="Tax-Free Capital Gains upon Maturity"
        ),
        BondItem(
            bond_name="7.18% GS 2033 (10-Year Benchmark G-Sec)",
            name="7.18% GS 2033 (10-Year Benchmark G-Sec)",
            symbol="718GS2033",
            isin="IN0020230085",
            category="G-Sec",
            issuer="Government of India",
            coupon_rate_pct=7.18,
            couponRate=7.18,
            ytm_pct=6.98,
            ytm=6.98,
            rating="Sovereign (AAA)",
            face_value=100.0,
            faceValue=100.0,
            market_price=101.40,
            ltp=101.40,
            maturity_date="2033-08-14",
            maturityDate="2033-08-14",
            tax_status="Taxable at slab rate"
        ),
        BondItem(
            bond_name="7.30% GS 2053 (Long-Duration Sovereign Debt)",
            name="7.30% GS 2053 (Long-Duration Sovereign Debt)",
            symbol="730GS2053",
            isin="IN0020230192",
            category="G-Sec",
            issuer="Government of India",
            coupon_rate_pct=7.30,
            couponRate=7.30,
            ytm_pct=7.15,
            ytm=7.15,
            rating="Sovereign (AAA)",
            face_value=100.0,
            faceValue=100.0,
            market_price=102.10,
            ltp=102.10,
            maturity_date="2053-05-22",
            maturityDate="2053-05-22",
            tax_status="Taxable at slab rate"
        ),
        BondItem(
            bond_name="National Highways Authority 7.90% 2030 (NHAI)",
            name="National Highways Authority 7.90% 2030 (NHAI)",
            symbol="NHAIBOND30",
            isin="INE906F07047",
            category="Corporate Bond",
            issuer="NHAI Ltd (Govt of India Undertaking)",
            coupon_rate_pct=7.90,
            couponRate=7.90,
            ytm_pct=7.45,
            ytm=7.45,
            rating="CRISIL AAA",
            face_value=1000.0,
            faceValue=1000.0,
            market_price=1022.50,
            ltp=1022.50,
            maturity_date="2030-03-31",
            maturityDate="2030-03-31",
            tax_status="Taxable at slab rate"
        ),
        BondItem(
            bond_name="REC Ltd 7.75% Tax-Free 2031",
            name="REC Ltd 7.75% Tax-Free 2031",
            symbol="RECTAXFREE",
            isin="INE020B07HR1",
            category="Corporate Bond",
            issuer="REC Limited (Govt PSU)",
            coupon_rate_pct=7.75,
            couponRate=7.75,
            ytm_pct=5.85,
            ytm=5.85,
            rating="ICRA AAA",
            face_value=1000.0,
            faceValue=1000.0,
            market_price=1140.0,
            ltp=1140.0,
            maturity_date="2031-10-15",
            maturityDate="2031-10-15",
            tax_status="100% Tax-Free Interest (Sec 10(15))"
        ),
        BondItem(
            bond_name="IRFC 7.55% Tax-Free 2033",
            name="IRFC 7.55% Tax-Free 2033",
            symbol="IRFCTAXFREE",
            isin="INE053F07936",
            category="Corporate Bond",
            issuer="Indian Railway Finance Corp (PSU)",
            coupon_rate_pct=7.55,
            couponRate=7.55,
            ytm_pct=5.72,
            ytm=5.72,
            rating="CRISIL AAA",
            face_value=1000.0,
            faceValue=1000.0,
            market_price=1165.0,
            ltp=1165.0,
            maturity_date="2033-03-24",
            maturityDate="2033-03-24",
            tax_status="100% Tax-Free Interest (Sec 10(15))"
        )
    ]

@router.get("/etfs", response_model=List[EtfItem])
def get_etfs():
    """Live ETFs Catalog across Index, Sectoral, Commodity, and Global assets."""
    return [
        EtfItem(
            symbol="NIFTYBEES",
            name="Nippon India Nifty 50 BeES ETF",
            underlyingAsset="Nifty 50 Index",
            category="Index ETF",
            current_nav=274.50,
            nav=274.50,
            ltp=274.50,
            day_change_pct=0.82,
            changePct=0.82,
            one_year_return_pct=26.40,
            three_year_cagr_pct=17.80,
            expense_ratio_pct=0.04,
            aum_cr=28450.0,
            aum=28450.0
        ),
        EtfItem(
            symbol="BANKBEES",
            name="Nippon India Nifty Bank BeES ETF",
            underlyingAsset="Nifty Bank Index",
            category="Sectoral ETF",
            current_nav=532.80,
            nav=532.80,
            ltp=532.80,
            day_change_pct=1.15,
            changePct=1.15,
            one_year_return_pct=18.20,
            three_year_cagr_pct=14.90,
            expense_ratio_pct=0.18,
            aum_cr=16200.0,
            aum=16200.0
        ),
        EtfItem(
            symbol="ITBEES",
            name="Nippon India Nifty IT BeES ETF",
            underlyingAsset="Nifty IT Index",
            category="Sectoral ETF",
            current_nav=43.80,
            nav=43.80,
            ltp=43.80,
            day_change_pct=1.92,
            changePct=1.92,
            one_year_return_pct=34.80,
            three_year_cagr_pct=19.40,
            expense_ratio_pct=0.22,
            aum_cr=7890.0,
            aum=7890.0
        ),
        EtfItem(
            symbol="GOLDBEES",
            name="Nippon India Gold ETF",
            underlyingAsset="Physical Gold (99.5% Purity)",
            category="Gold & Silver",
            current_nav=64.20,
            nav=64.20,
            ltp=64.20,
            day_change_pct=-0.25,
            changePct=-0.25,
            one_year_return_pct=24.50,
            three_year_cagr_pct=16.20,
            expense_ratio_pct=0.79,
            aum_cr=14500.0,
            aum=14500.0
        ),
        EtfItem(
            symbol="SILVERBEES",
            name="Nippon India Silver ETF",
            underlyingAsset="Physical Silver (99.9% Purity)",
            category="Gold & Silver",
            current_nav=86.40,
            nav=86.40,
            ltp=86.40,
            day_change_pct=0.45,
            changePct=0.45,
            one_year_return_pct=28.10,
            three_year_cagr_pct=21.40,
            expense_ratio_pct=0.55,
            aum_cr=4300.0,
            aum=4300.0
        ),
        EtfItem(
            symbol="MON100",
            name="Motilal Oswal Nasdaq 100 ETF",
            underlyingAsset="Nasdaq 100 Index",
            category="Global ETF",
            current_nav=162.80,
            nav=162.80,
            ltp=162.80,
            day_change_pct=1.40,
            changePct=1.40,
            one_year_return_pct=36.80,
            three_year_cagr_pct=23.50,
            expense_ratio_pct=0.58,
            aum_cr=6800.0,
            aum=6800.0
        ),
        EtfItem(
            symbol="JUNIORBEES",
            name="Nippon India Nifty Next 50 Junior BeES ETF",
            underlyingAsset="Nifty Next 50 Index",
            category="Index ETF",
            current_nav=742.00,
            nav=742.00,
            ltp=742.00,
            day_change_pct=1.05,
            changePct=1.05,
            one_year_return_pct=48.50,
            three_year_cagr_pct=24.20,
            expense_ratio_pct=0.12,
            aum_cr=5100.0,
            aum=5100.0
        ),
        EtfItem(
            symbol="CPSEETF",
            name="CPSE ETF (Top Central Public Sector Equities)",
            underlyingAsset="Nifty CPSE Index",
            category="Sectoral ETF",
            current_nav=94.50,
            nav=94.50,
            ltp=94.50,
            day_change_pct=2.15,
            changePct=2.15,
            one_year_return_pct=64.20,
            three_year_cagr_pct=38.40,
            expense_ratio_pct=0.05,
            aum_cr=42100.0,
            aum=42100.0
        )
    ]
